name: "Build 🚀"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/pytorch-keynote-2024/symphony
          tags: |
            type=sha,format=long
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/pytorch-keynote-2024/symphony:cache-amd64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/pytorch-keynote-2024/symphony:cache-arm64
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/pytorch-keynote-2024/symphony:cache-amd64,mode=max,ignore-error=true
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/pytorch-keynote-2024/symphony:cache-arm64,mode=max,ignore-error=true
